[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "https://wordcloud.click/socket.io/:splat"
  status = 200
  force = true
  headers = { Connection = "Upgrade", Upgrade = "websocket" }

[build]
  publish = "build"
  command = "CI=false npm run build"
  ignore = "git diff --quiet HEAD^ HEAD ."